name: Release

on:
  push:
    branches: main

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'
          check-latest: true
      
      - name: Build
        run: go build
      
      - name: Get version
        run: |
          echo "RELEASE_VERSION=$(./movies-app version)" >> $GITHUB_ENV
      
      - name: Tag Commit
        id: tag_commit
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.RELEASE_VERSION }}
          tag_prefix: ""
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: movies-app
          tag_name: ${{ steps.tag_commit.outputs.new_tag }}
