name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment.
        run: |
          echo PERSONAL_GCP_PROJECT=${{ secrets.PERSONAL_PROJECT_ID }} >> $GITHUB_ENV
          echo TAG_NAME=${{ github.event.release.tag_name }} >> $GITHUB_ENV

      - name: Login Docker to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.MOVIES_APP_CICD_SERVICE_ACCOUNT_KEY }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: app
          push: true
          tags: gcr.io/${{ secrets.PERSONAL_PROJECT_ID }}:${{ github.event.release.tag_name }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.PERSONAL_PROJECT_ID }}
          service_account_key: ${{ secrets.MOVIES_APP_CICD_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Deploy
        run: |
          gcloud run deploy movies-app \
            --image gcr.io/${{ secrets.PERSONAL_PROJECT_ID }}:${{ github.event.release.tag_name }} \
            --platform managed \
            --max-instances 1 \
            --service-account movies-app@${{ secrets.PERSONAL_PROJECT_ID }}.iam.gserviceaccount.com \
            --set-env-vars "GOOGLE_CLOUD_PROJECT=${{ secrets.PERSONAL_PROJECT_ID }}" \
            --region us-central1
