name: Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'
          check-latest: true
      
      - name: Test
        run: go test -v ./cmd