name: Update Movie Data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # See https://github.com/marketplace/actions/github-push#example-workflow-file
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up environment
        run: |
          echo OMDB_KEY=${{ secrets.OMDB_KEY }} >> $GITHUB_ENV
          echo NOTION_KEY=${{ secrets.NOTION_KEY }} >> $GITHUB_ENV

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          
      - name: Authorize Gcloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.MOVIE_DVC_PUSHER_SA_CREDS }}"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Set up git.
        # See https://github.com/marketplace/actions/github-push#example-workflow-file
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Pull DVC
        run: dvc pull

      - name: Pull Notion data
        run: python scripts/pull_notion.py --output-file data/raw/notion_out.json

      - name: Run DVC repro
        run: dvc repro

      - name: git add
        continue-on-error: true
        run: |
          git add dvc.lock data/
          timestamp=$(date -u)
          git commit -m "Update datasets: ${timestamp}."

      - name: git push
        # See https://github.com/marketplace/actions/github-push#example-workflow-file
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: dvc push
        run: dvc push
