name: Update Movie Data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # See https://github.com/marketplace/actions/github-push#example-workflow-file
        with:
          persist-credentials: false
          fetch-depth: 0
      
      - name: Set up git.
        # See https://github.com/marketplace/actions/github-push#example-workflow-file
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      
      - name: Set up movies-app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download \
            --repo timothyrenner/movies-app \
            --pattern movies-app
          chmod a+x movies-app

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          
      - name: Authorize Gcloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.MOVIE_DVC_PUSHER_SA_CREDS }}"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Pull DVC
        run: dvc pull

      - name: Update Movies
        env:
          GRIST_KEY: ${{ secrets.GRIST_KEY }}
          GRIST_DOCUMENT_ID: ${{ secrets.GRIST_DOCUMENT_ID }}
          OMDB_KEY: ${{ secrets.OMDB_KEY }}
        run: ./movies-app update-movies -l 10 
        

      - name: DVC Add
        run: dvc add data/movies.db

      - name: git add
        continue-on-error: true
        run: |
          git add data/
          timestamp=$(date -u)
          git commit -m "Update datasets: ${timestamp}."

      - name: git push
        # See https://github.com/marketplace/actions/github-push#example-workflow-file
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: dvc push
        run: dvc push
