// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Movie         string
	MovieActor    string
	MovieDirector string
	MovieGenre    string
	MovieRating   string
	MovieWatch    string
	MovieWriter   string
}{
	Movie:         "movie",
	MovieActor:    "movie_actor",
	MovieDirector: "movie_director",
	MovieGenre:    "movie_genre",
	MovieRating:   "movie_rating",
	MovieWatch:    "movie_watch",
	MovieWriter:   "movie_writer",
}
