// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// MovieWatch is an object representing the database table.
type MovieWatch struct {
	UUID            null.String `boil:"uuid" json:"uuid,omitempty" toml:"uuid" yaml:"uuid,omitempty"`
	MovieUUID       null.String `boil:"movie_uuid" json:"movie_uuid,omitempty" toml:"movie_uuid" yaml:"movie_uuid,omitempty"`
	MovieTitle      null.String `boil:"movie_title" json:"movie_title,omitempty" toml:"movie_title" yaml:"movie_title,omitempty"`
	Service         string      `boil:"service" json:"service" toml:"service" yaml:"service"`
	FirstTime       int64       `boil:"first_time" json:"first_time" toml:"first_time" yaml:"first_time"`
	JoeBob          int64       `boil:"joe_bob" json:"joe_bob" toml:"joe_bob" yaml:"joe_bob"`
	CreatedDatetime int64       `boil:"created_datetime" json:"created_datetime" toml:"created_datetime" yaml:"created_datetime"`
	ImdbID          string      `boil:"imdb_id" json:"imdb_id" toml:"imdb_id" yaml:"imdb_id"`
	Watched         null.String `boil:"watched" json:"watched,omitempty" toml:"watched" yaml:"watched,omitempty"`
	Notes           null.String `boil:"notes" json:"notes,omitempty" toml:"notes" yaml:"notes,omitempty"`

	R *movieWatchR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L movieWatchL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var MovieWatchColumns = struct {
	UUID            string
	MovieUUID       string
	MovieTitle      string
	Service         string
	FirstTime       string
	JoeBob          string
	CreatedDatetime string
	ImdbID          string
	Watched         string
	Notes           string
}{
	UUID:            "uuid",
	MovieUUID:       "movie_uuid",
	MovieTitle:      "movie_title",
	Service:         "service",
	FirstTime:       "first_time",
	JoeBob:          "joe_bob",
	CreatedDatetime: "created_datetime",
	ImdbID:          "imdb_id",
	Watched:         "watched",
	Notes:           "notes",
}

var MovieWatchTableColumns = struct {
	UUID            string
	MovieUUID       string
	MovieTitle      string
	Service         string
	FirstTime       string
	JoeBob          string
	CreatedDatetime string
	ImdbID          string
	Watched         string
	Notes           string
}{
	UUID:            "movie_watch.uuid",
	MovieUUID:       "movie_watch.movie_uuid",
	MovieTitle:      "movie_watch.movie_title",
	Service:         "movie_watch.service",
	FirstTime:       "movie_watch.first_time",
	JoeBob:          "movie_watch.joe_bob",
	CreatedDatetime: "movie_watch.created_datetime",
	ImdbID:          "movie_watch.imdb_id",
	Watched:         "movie_watch.watched",
	Notes:           "movie_watch.notes",
}

// Generated where

var MovieWatchWhere = struct {
	UUID            whereHelpernull_String
	MovieUUID       whereHelpernull_String
	MovieTitle      whereHelpernull_String
	Service         whereHelperstring
	FirstTime       whereHelperint64
	JoeBob          whereHelperint64
	CreatedDatetime whereHelperint64
	ImdbID          whereHelperstring
	Watched         whereHelpernull_String
	Notes           whereHelpernull_String
}{
	UUID:            whereHelpernull_String{field: "\"movie_watch\".\"uuid\""},
	MovieUUID:       whereHelpernull_String{field: "\"movie_watch\".\"movie_uuid\""},
	MovieTitle:      whereHelpernull_String{field: "\"movie_watch\".\"movie_title\""},
	Service:         whereHelperstring{field: "\"movie_watch\".\"service\""},
	FirstTime:       whereHelperint64{field: "\"movie_watch\".\"first_time\""},
	JoeBob:          whereHelperint64{field: "\"movie_watch\".\"joe_bob\""},
	CreatedDatetime: whereHelperint64{field: "\"movie_watch\".\"created_datetime\""},
	ImdbID:          whereHelperstring{field: "\"movie_watch\".\"imdb_id\""},
	Watched:         whereHelpernull_String{field: "\"movie_watch\".\"watched\""},
	Notes:           whereHelpernull_String{field: "\"movie_watch\".\"notes\""},
}

// MovieWatchRels is where relationship names are stored.
var MovieWatchRels = struct {
	Movie string
}{
	Movie: "Movie",
}

// movieWatchR is where relationships are stored.
type movieWatchR struct {
	Movie *Movie `boil:"Movie" json:"Movie" toml:"Movie" yaml:"Movie"`
}

// NewStruct creates a new relationship struct
func (*movieWatchR) NewStruct() *movieWatchR {
	return &movieWatchR{}
}

func (r *movieWatchR) GetMovie() *Movie {
	if r == nil {
		return nil
	}
	return r.Movie
}

// movieWatchL is where Load methods for each relationship are stored.
type movieWatchL struct{}

var (
	movieWatchAllColumns            = []string{"uuid", "movie_uuid", "movie_title", "service", "first_time", "joe_bob", "created_datetime", "imdb_id", "watched", "notes"}
	movieWatchColumnsWithoutDefault = []string{"service", "first_time", "joe_bob"}
	movieWatchColumnsWithDefault    = []string{"uuid", "movie_uuid", "movie_title", "created_datetime", "imdb_id", "watched", "notes"}
	movieWatchPrimaryKeyColumns     = []string{"uuid"}
	movieWatchGeneratedColumns      = []string{}
)

type (
	// MovieWatchSlice is an alias for a slice of pointers to MovieWatch.
	// This should almost always be used instead of []MovieWatch.
	MovieWatchSlice []*MovieWatch

	movieWatchQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	movieWatchType                 = reflect.TypeOf(&MovieWatch{})
	movieWatchMapping              = queries.MakeStructMapping(movieWatchType)
	movieWatchPrimaryKeyMapping, _ = queries.BindMapping(movieWatchType, movieWatchMapping, movieWatchPrimaryKeyColumns)
	movieWatchInsertCacheMut       sync.RWMutex
	movieWatchInsertCache          = make(map[string]insertCache)
	movieWatchUpdateCacheMut       sync.RWMutex
	movieWatchUpdateCache          = make(map[string]updateCache)
	movieWatchUpsertCacheMut       sync.RWMutex
	movieWatchUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single movieWatch record from the query.
func (q movieWatchQuery) One(ctx context.Context, exec boil.ContextExecutor) (*MovieWatch, error) {
	o := &MovieWatch{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for movie_watch")
	}

	return o, nil
}

// All returns all MovieWatch records from the query.
func (q movieWatchQuery) All(ctx context.Context, exec boil.ContextExecutor) (MovieWatchSlice, error) {
	var o []*MovieWatch

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to MovieWatch slice")
	}

	return o, nil
}

// Count returns the count of all MovieWatch records in the query.
func (q movieWatchQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count movie_watch rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q movieWatchQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if movie_watch exists")
	}

	return count > 0, nil
}

// Movie pointed to by the foreign key.
func (o *MovieWatch) Movie(mods ...qm.QueryMod) movieQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"uuid\" = ?", o.MovieUUID),
	}

	queryMods = append(queryMods, mods...)

	return Movies(queryMods...)
}

// LoadMovie allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (movieWatchL) LoadMovie(ctx context.Context, e boil.ContextExecutor, singular bool, maybeMovieWatch interface{}, mods queries.Applicator) error {
	var slice []*MovieWatch
	var object *MovieWatch

	if singular {
		var ok bool
		object, ok = maybeMovieWatch.(*MovieWatch)
		if !ok {
			object = new(MovieWatch)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeMovieWatch)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeMovieWatch))
			}
		}
	} else {
		s, ok := maybeMovieWatch.(*[]*MovieWatch)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeMovieWatch)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeMovieWatch))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &movieWatchR{}
		}
		if !queries.IsNil(object.MovieUUID) {
			args = append(args, object.MovieUUID)
		}

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &movieWatchR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.MovieUUID) {
					continue Outer
				}
			}

			if !queries.IsNil(obj.MovieUUID) {
				args = append(args, obj.MovieUUID)
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`movie`),
		qm.WhereIn(`movie.uuid in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Movie")
	}

	var resultSlice []*Movie
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Movie")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for movie")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for movie")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Movie = foreign
		if foreign.R == nil {
			foreign.R = &movieR{}
		}
		foreign.R.MovieWatches = append(foreign.R.MovieWatches, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.MovieUUID, foreign.UUID) {
				local.R.Movie = foreign
				if foreign.R == nil {
					foreign.R = &movieR{}
				}
				foreign.R.MovieWatches = append(foreign.R.MovieWatches, local)
				break
			}
		}
	}

	return nil
}

// SetMovie of the movieWatch to the related item.
// Sets o.R.Movie to related.
// Adds o to related.R.MovieWatches.
func (o *MovieWatch) SetMovie(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Movie) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"movie_watch\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"movie_uuid"}),
		strmangle.WhereClause("\"", "\"", 0, movieWatchPrimaryKeyColumns),
	)
	values := []interface{}{related.UUID, o.UUID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.MovieUUID, related.UUID)
	if o.R == nil {
		o.R = &movieWatchR{
			Movie: related,
		}
	} else {
		o.R.Movie = related
	}

	if related.R == nil {
		related.R = &movieR{
			MovieWatches: MovieWatchSlice{o},
		}
	} else {
		related.R.MovieWatches = append(related.R.MovieWatches, o)
	}

	return nil
}

// RemoveMovie relationship.
// Sets o.R.Movie to nil.
// Removes o from all passed in related items' relationships struct.
func (o *MovieWatch) RemoveMovie(ctx context.Context, exec boil.ContextExecutor, related *Movie) error {
	var err error

	queries.SetScanner(&o.MovieUUID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("movie_uuid")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Movie = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.MovieWatches {
		if queries.Equal(o.MovieUUID, ri.MovieUUID) {
			continue
		}

		ln := len(related.R.MovieWatches)
		if ln > 1 && i < ln-1 {
			related.R.MovieWatches[i] = related.R.MovieWatches[ln-1]
		}
		related.R.MovieWatches = related.R.MovieWatches[:ln-1]
		break
	}
	return nil
}

// MovieWatches retrieves all the records using an executor.
func MovieWatches(mods ...qm.QueryMod) movieWatchQuery {
	mods = append(mods, qm.From("\"movie_watch\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"movie_watch\".*"})
	}

	return movieWatchQuery{q}
}

// FindMovieWatch retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindMovieWatch(ctx context.Context, exec boil.ContextExecutor, uUID null.String, selectCols ...string) (*MovieWatch, error) {
	movieWatchObj := &MovieWatch{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"movie_watch\" where \"uuid\"=?", sel,
	)

	q := queries.Raw(query, uUID)

	err := q.Bind(ctx, exec, movieWatchObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from movie_watch")
	}

	return movieWatchObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *MovieWatch) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no movie_watch provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(movieWatchColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	movieWatchInsertCacheMut.RLock()
	cache, cached := movieWatchInsertCache[key]
	movieWatchInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			movieWatchAllColumns,
			movieWatchColumnsWithDefault,
			movieWatchColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(movieWatchType, movieWatchMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(movieWatchType, movieWatchMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"movie_watch\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"movie_watch\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into movie_watch")
	}

	if !cached {
		movieWatchInsertCacheMut.Lock()
		movieWatchInsertCache[key] = cache
		movieWatchInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the MovieWatch.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *MovieWatch) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	movieWatchUpdateCacheMut.RLock()
	cache, cached := movieWatchUpdateCache[key]
	movieWatchUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			movieWatchAllColumns,
			movieWatchPrimaryKeyColumns,
		)
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update movie_watch, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"movie_watch\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, movieWatchPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(movieWatchType, movieWatchMapping, append(wl, movieWatchPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update movie_watch row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for movie_watch")
	}

	if !cached {
		movieWatchUpdateCacheMut.Lock()
		movieWatchUpdateCache[key] = cache
		movieWatchUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q movieWatchQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for movie_watch")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for movie_watch")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o MovieWatchSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), movieWatchPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"movie_watch\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, movieWatchPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in movieWatch slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all movieWatch")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *MovieWatch) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no movie_watch provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(movieWatchColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	movieWatchUpsertCacheMut.RLock()
	cache, cached := movieWatchUpsertCache[key]
	movieWatchUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			movieWatchAllColumns,
			movieWatchColumnsWithDefault,
			movieWatchColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			movieWatchAllColumns,
			movieWatchPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert movie_watch, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(movieWatchPrimaryKeyColumns))
			copy(conflict, movieWatchPrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"movie_watch\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(movieWatchType, movieWatchMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(movieWatchType, movieWatchMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert movie_watch")
	}

	if !cached {
		movieWatchUpsertCacheMut.Lock()
		movieWatchUpsertCache[key] = cache
		movieWatchUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single MovieWatch record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *MovieWatch) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no MovieWatch provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), movieWatchPrimaryKeyMapping)
	sql := "DELETE FROM \"movie_watch\" WHERE \"uuid\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from movie_watch")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for movie_watch")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q movieWatchQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no movieWatchQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from movie_watch")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for movie_watch")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o MovieWatchSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), movieWatchPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"movie_watch\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, movieWatchPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from movieWatch slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for movie_watch")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *MovieWatch) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindMovieWatch(ctx, exec, o.UUID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *MovieWatchSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := MovieWatchSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), movieWatchPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"movie_watch\".* FROM \"movie_watch\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, movieWatchPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in MovieWatchSlice")
	}

	*o = slice

	return nil
}

// MovieWatchExists checks if the MovieWatch row exists.
func MovieWatchExists(ctx context.Context, exec boil.ContextExecutor, uUID null.String) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"movie_watch\" where \"uuid\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, uUID)
	}
	row := exec.QueryRowContext(ctx, sql, uUID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if movie_watch exists")
	}

	return exists, nil
}
