// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// MovieDirector is an object representing the database table.
type MovieDirector struct {
	UUID            null.String `boil:"uuid" json:"uuid,omitempty" toml:"uuid" yaml:"uuid,omitempty"`
	MovieUUID       null.String `boil:"movie_uuid" json:"movie_uuid,omitempty" toml:"movie_uuid" yaml:"movie_uuid,omitempty"`
	Name            string      `boil:"name" json:"name" toml:"name" yaml:"name"`
	CreatedDatetime int64       `boil:"created_datetime" json:"created_datetime" toml:"created_datetime" yaml:"created_datetime"`

	R *movieDirectorR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L movieDirectorL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var MovieDirectorColumns = struct {
	UUID            string
	MovieUUID       string
	Name            string
	CreatedDatetime string
}{
	UUID:            "uuid",
	MovieUUID:       "movie_uuid",
	Name:            "name",
	CreatedDatetime: "created_datetime",
}

var MovieDirectorTableColumns = struct {
	UUID            string
	MovieUUID       string
	Name            string
	CreatedDatetime string
}{
	UUID:            "movie_director.uuid",
	MovieUUID:       "movie_director.movie_uuid",
	Name:            "movie_director.name",
	CreatedDatetime: "movie_director.created_datetime",
}

// Generated where

var MovieDirectorWhere = struct {
	UUID            whereHelpernull_String
	MovieUUID       whereHelpernull_String
	Name            whereHelperstring
	CreatedDatetime whereHelperint64
}{
	UUID:            whereHelpernull_String{field: "\"movie_director\".\"uuid\""},
	MovieUUID:       whereHelpernull_String{field: "\"movie_director\".\"movie_uuid\""},
	Name:            whereHelperstring{field: "\"movie_director\".\"name\""},
	CreatedDatetime: whereHelperint64{field: "\"movie_director\".\"created_datetime\""},
}

// MovieDirectorRels is where relationship names are stored.
var MovieDirectorRels = struct {
	Movie string
}{
	Movie: "Movie",
}

// movieDirectorR is where relationships are stored.
type movieDirectorR struct {
	Movie *Movie `boil:"Movie" json:"Movie" toml:"Movie" yaml:"Movie"`
}

// NewStruct creates a new relationship struct
func (*movieDirectorR) NewStruct() *movieDirectorR {
	return &movieDirectorR{}
}

func (r *movieDirectorR) GetMovie() *Movie {
	if r == nil {
		return nil
	}
	return r.Movie
}

// movieDirectorL is where Load methods for each relationship are stored.
type movieDirectorL struct{}

var (
	movieDirectorAllColumns            = []string{"uuid", "movie_uuid", "name", "created_datetime"}
	movieDirectorColumnsWithoutDefault = []string{"name"}
	movieDirectorColumnsWithDefault    = []string{"uuid", "movie_uuid", "created_datetime"}
	movieDirectorPrimaryKeyColumns     = []string{"uuid"}
	movieDirectorGeneratedColumns      = []string{}
)

type (
	// MovieDirectorSlice is an alias for a slice of pointers to MovieDirector.
	// This should almost always be used instead of []MovieDirector.
	MovieDirectorSlice []*MovieDirector

	movieDirectorQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	movieDirectorType                 = reflect.TypeOf(&MovieDirector{})
	movieDirectorMapping              = queries.MakeStructMapping(movieDirectorType)
	movieDirectorPrimaryKeyMapping, _ = queries.BindMapping(movieDirectorType, movieDirectorMapping, movieDirectorPrimaryKeyColumns)
	movieDirectorInsertCacheMut       sync.RWMutex
	movieDirectorInsertCache          = make(map[string]insertCache)
	movieDirectorUpdateCacheMut       sync.RWMutex
	movieDirectorUpdateCache          = make(map[string]updateCache)
	movieDirectorUpsertCacheMut       sync.RWMutex
	movieDirectorUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single movieDirector record from the query.
func (q movieDirectorQuery) One(ctx context.Context, exec boil.ContextExecutor) (*MovieDirector, error) {
	o := &MovieDirector{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for movie_director")
	}

	return o, nil
}

// All returns all MovieDirector records from the query.
func (q movieDirectorQuery) All(ctx context.Context, exec boil.ContextExecutor) (MovieDirectorSlice, error) {
	var o []*MovieDirector

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to MovieDirector slice")
	}

	return o, nil
}

// Count returns the count of all MovieDirector records in the query.
func (q movieDirectorQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count movie_director rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q movieDirectorQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if movie_director exists")
	}

	return count > 0, nil
}

// Movie pointed to by the foreign key.
func (o *MovieDirector) Movie(mods ...qm.QueryMod) movieQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"uuid\" = ?", o.MovieUUID),
	}

	queryMods = append(queryMods, mods...)

	return Movies(queryMods...)
}

// LoadMovie allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (movieDirectorL) LoadMovie(ctx context.Context, e boil.ContextExecutor, singular bool, maybeMovieDirector interface{}, mods queries.Applicator) error {
	var slice []*MovieDirector
	var object *MovieDirector

	if singular {
		var ok bool
		object, ok = maybeMovieDirector.(*MovieDirector)
		if !ok {
			object = new(MovieDirector)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeMovieDirector)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeMovieDirector))
			}
		}
	} else {
		s, ok := maybeMovieDirector.(*[]*MovieDirector)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeMovieDirector)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeMovieDirector))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &movieDirectorR{}
		}
		if !queries.IsNil(object.MovieUUID) {
			args = append(args, object.MovieUUID)
		}

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &movieDirectorR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.MovieUUID) {
					continue Outer
				}
			}

			if !queries.IsNil(obj.MovieUUID) {
				args = append(args, obj.MovieUUID)
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`movie`),
		qm.WhereIn(`movie.uuid in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Movie")
	}

	var resultSlice []*Movie
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Movie")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for movie")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for movie")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Movie = foreign
		if foreign.R == nil {
			foreign.R = &movieR{}
		}
		foreign.R.MovieDirectors = append(foreign.R.MovieDirectors, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.MovieUUID, foreign.UUID) {
				local.R.Movie = foreign
				if foreign.R == nil {
					foreign.R = &movieR{}
				}
				foreign.R.MovieDirectors = append(foreign.R.MovieDirectors, local)
				break
			}
		}
	}

	return nil
}

// SetMovie of the movieDirector to the related item.
// Sets o.R.Movie to related.
// Adds o to related.R.MovieDirectors.
func (o *MovieDirector) SetMovie(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Movie) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"movie_director\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"movie_uuid"}),
		strmangle.WhereClause("\"", "\"", 0, movieDirectorPrimaryKeyColumns),
	)
	values := []interface{}{related.UUID, o.UUID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.MovieUUID, related.UUID)
	if o.R == nil {
		o.R = &movieDirectorR{
			Movie: related,
		}
	} else {
		o.R.Movie = related
	}

	if related.R == nil {
		related.R = &movieR{
			MovieDirectors: MovieDirectorSlice{o},
		}
	} else {
		related.R.MovieDirectors = append(related.R.MovieDirectors, o)
	}

	return nil
}

// RemoveMovie relationship.
// Sets o.R.Movie to nil.
// Removes o from all passed in related items' relationships struct.
func (o *MovieDirector) RemoveMovie(ctx context.Context, exec boil.ContextExecutor, related *Movie) error {
	var err error

	queries.SetScanner(&o.MovieUUID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("movie_uuid")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Movie = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.MovieDirectors {
		if queries.Equal(o.MovieUUID, ri.MovieUUID) {
			continue
		}

		ln := len(related.R.MovieDirectors)
		if ln > 1 && i < ln-1 {
			related.R.MovieDirectors[i] = related.R.MovieDirectors[ln-1]
		}
		related.R.MovieDirectors = related.R.MovieDirectors[:ln-1]
		break
	}
	return nil
}

// MovieDirectors retrieves all the records using an executor.
func MovieDirectors(mods ...qm.QueryMod) movieDirectorQuery {
	mods = append(mods, qm.From("\"movie_director\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"movie_director\".*"})
	}

	return movieDirectorQuery{q}
}

// FindMovieDirector retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindMovieDirector(ctx context.Context, exec boil.ContextExecutor, uUID null.String, selectCols ...string) (*MovieDirector, error) {
	movieDirectorObj := &MovieDirector{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"movie_director\" where \"uuid\"=?", sel,
	)

	q := queries.Raw(query, uUID)

	err := q.Bind(ctx, exec, movieDirectorObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from movie_director")
	}

	return movieDirectorObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *MovieDirector) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no movie_director provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(movieDirectorColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	movieDirectorInsertCacheMut.RLock()
	cache, cached := movieDirectorInsertCache[key]
	movieDirectorInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			movieDirectorAllColumns,
			movieDirectorColumnsWithDefault,
			movieDirectorColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(movieDirectorType, movieDirectorMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(movieDirectorType, movieDirectorMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"movie_director\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"movie_director\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into movie_director")
	}

	if !cached {
		movieDirectorInsertCacheMut.Lock()
		movieDirectorInsertCache[key] = cache
		movieDirectorInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the MovieDirector.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *MovieDirector) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	movieDirectorUpdateCacheMut.RLock()
	cache, cached := movieDirectorUpdateCache[key]
	movieDirectorUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			movieDirectorAllColumns,
			movieDirectorPrimaryKeyColumns,
		)
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update movie_director, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"movie_director\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, movieDirectorPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(movieDirectorType, movieDirectorMapping, append(wl, movieDirectorPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update movie_director row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for movie_director")
	}

	if !cached {
		movieDirectorUpdateCacheMut.Lock()
		movieDirectorUpdateCache[key] = cache
		movieDirectorUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q movieDirectorQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for movie_director")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for movie_director")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o MovieDirectorSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), movieDirectorPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"movie_director\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, movieDirectorPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in movieDirector slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all movieDirector")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *MovieDirector) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no movie_director provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(movieDirectorColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	movieDirectorUpsertCacheMut.RLock()
	cache, cached := movieDirectorUpsertCache[key]
	movieDirectorUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			movieDirectorAllColumns,
			movieDirectorColumnsWithDefault,
			movieDirectorColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			movieDirectorAllColumns,
			movieDirectorPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert movie_director, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(movieDirectorPrimaryKeyColumns))
			copy(conflict, movieDirectorPrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"movie_director\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(movieDirectorType, movieDirectorMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(movieDirectorType, movieDirectorMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert movie_director")
	}

	if !cached {
		movieDirectorUpsertCacheMut.Lock()
		movieDirectorUpsertCache[key] = cache
		movieDirectorUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single MovieDirector record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *MovieDirector) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no MovieDirector provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), movieDirectorPrimaryKeyMapping)
	sql := "DELETE FROM \"movie_director\" WHERE \"uuid\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from movie_director")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for movie_director")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q movieDirectorQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no movieDirectorQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from movie_director")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for movie_director")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o MovieDirectorSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), movieDirectorPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"movie_director\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, movieDirectorPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from movieDirector slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for movie_director")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *MovieDirector) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindMovieDirector(ctx, exec, o.UUID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *MovieDirectorSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := MovieDirectorSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), movieDirectorPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"movie_director\".* FROM \"movie_director\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, movieDirectorPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in MovieDirectorSlice")
	}

	*o = slice

	return nil
}

// MovieDirectorExists checks if the MovieDirector row exists.
func MovieDirectorExists(ctx context.Context, exec boil.ContextExecutor, uUID null.String) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"movie_director\" where \"uuid\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, uUID)
	}
	row := exec.QueryRowContext(ctx, sql, uUID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if movie_director exists")
	}

	return exists, nil
}
