// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// MovieWriter is an object representing the database table.
type MovieWriter struct {
	UUID            null.String `boil:"uuid" json:"uuid,omitempty" toml:"uuid" yaml:"uuid,omitempty"`
	MovieUUID       null.String `boil:"movie_uuid" json:"movie_uuid,omitempty" toml:"movie_uuid" yaml:"movie_uuid,omitempty"`
	Name            string      `boil:"name" json:"name" toml:"name" yaml:"name"`
	CreatedDatetime int64       `boil:"created_datetime" json:"created_datetime" toml:"created_datetime" yaml:"created_datetime"`

	R *movieWriterR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L movieWriterL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var MovieWriterColumns = struct {
	UUID            string
	MovieUUID       string
	Name            string
	CreatedDatetime string
}{
	UUID:            "uuid",
	MovieUUID:       "movie_uuid",
	Name:            "name",
	CreatedDatetime: "created_datetime",
}

var MovieWriterTableColumns = struct {
	UUID            string
	MovieUUID       string
	Name            string
	CreatedDatetime string
}{
	UUID:            "movie_writer.uuid",
	MovieUUID:       "movie_writer.movie_uuid",
	Name:            "movie_writer.name",
	CreatedDatetime: "movie_writer.created_datetime",
}

// Generated where

var MovieWriterWhere = struct {
	UUID            whereHelpernull_String
	MovieUUID       whereHelpernull_String
	Name            whereHelperstring
	CreatedDatetime whereHelperint64
}{
	UUID:            whereHelpernull_String{field: "\"movie_writer\".\"uuid\""},
	MovieUUID:       whereHelpernull_String{field: "\"movie_writer\".\"movie_uuid\""},
	Name:            whereHelperstring{field: "\"movie_writer\".\"name\""},
	CreatedDatetime: whereHelperint64{field: "\"movie_writer\".\"created_datetime\""},
}

// MovieWriterRels is where relationship names are stored.
var MovieWriterRels = struct {
	Movie string
}{
	Movie: "Movie",
}

// movieWriterR is where relationships are stored.
type movieWriterR struct {
	Movie *Movie `boil:"Movie" json:"Movie" toml:"Movie" yaml:"Movie"`
}

// NewStruct creates a new relationship struct
func (*movieWriterR) NewStruct() *movieWriterR {
	return &movieWriterR{}
}

func (r *movieWriterR) GetMovie() *Movie {
	if r == nil {
		return nil
	}
	return r.Movie
}

// movieWriterL is where Load methods for each relationship are stored.
type movieWriterL struct{}

var (
	movieWriterAllColumns            = []string{"uuid", "movie_uuid", "name", "created_datetime"}
	movieWriterColumnsWithoutDefault = []string{"name"}
	movieWriterColumnsWithDefault    = []string{"uuid", "movie_uuid", "created_datetime"}
	movieWriterPrimaryKeyColumns     = []string{"uuid"}
	movieWriterGeneratedColumns      = []string{}
)

type (
	// MovieWriterSlice is an alias for a slice of pointers to MovieWriter.
	// This should almost always be used instead of []MovieWriter.
	MovieWriterSlice []*MovieWriter

	movieWriterQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	movieWriterType                 = reflect.TypeOf(&MovieWriter{})
	movieWriterMapping              = queries.MakeStructMapping(movieWriterType)
	movieWriterPrimaryKeyMapping, _ = queries.BindMapping(movieWriterType, movieWriterMapping, movieWriterPrimaryKeyColumns)
	movieWriterInsertCacheMut       sync.RWMutex
	movieWriterInsertCache          = make(map[string]insertCache)
	movieWriterUpdateCacheMut       sync.RWMutex
	movieWriterUpdateCache          = make(map[string]updateCache)
	movieWriterUpsertCacheMut       sync.RWMutex
	movieWriterUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single movieWriter record from the query.
func (q movieWriterQuery) One(ctx context.Context, exec boil.ContextExecutor) (*MovieWriter, error) {
	o := &MovieWriter{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for movie_writer")
	}

	return o, nil
}

// All returns all MovieWriter records from the query.
func (q movieWriterQuery) All(ctx context.Context, exec boil.ContextExecutor) (MovieWriterSlice, error) {
	var o []*MovieWriter

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to MovieWriter slice")
	}

	return o, nil
}

// Count returns the count of all MovieWriter records in the query.
func (q movieWriterQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count movie_writer rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q movieWriterQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if movie_writer exists")
	}

	return count > 0, nil
}

// Movie pointed to by the foreign key.
func (o *MovieWriter) Movie(mods ...qm.QueryMod) movieQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"uuid\" = ?", o.MovieUUID),
	}

	queryMods = append(queryMods, mods...)

	return Movies(queryMods...)
}

// LoadMovie allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (movieWriterL) LoadMovie(ctx context.Context, e boil.ContextExecutor, singular bool, maybeMovieWriter interface{}, mods queries.Applicator) error {
	var slice []*MovieWriter
	var object *MovieWriter

	if singular {
		var ok bool
		object, ok = maybeMovieWriter.(*MovieWriter)
		if !ok {
			object = new(MovieWriter)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeMovieWriter)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeMovieWriter))
			}
		}
	} else {
		s, ok := maybeMovieWriter.(*[]*MovieWriter)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeMovieWriter)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeMovieWriter))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &movieWriterR{}
		}
		if !queries.IsNil(object.MovieUUID) {
			args = append(args, object.MovieUUID)
		}

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &movieWriterR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.MovieUUID) {
					continue Outer
				}
			}

			if !queries.IsNil(obj.MovieUUID) {
				args = append(args, obj.MovieUUID)
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`movie`),
		qm.WhereIn(`movie.uuid in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Movie")
	}

	var resultSlice []*Movie
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Movie")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for movie")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for movie")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Movie = foreign
		if foreign.R == nil {
			foreign.R = &movieR{}
		}
		foreign.R.MovieWriters = append(foreign.R.MovieWriters, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.MovieUUID, foreign.UUID) {
				local.R.Movie = foreign
				if foreign.R == nil {
					foreign.R = &movieR{}
				}
				foreign.R.MovieWriters = append(foreign.R.MovieWriters, local)
				break
			}
		}
	}

	return nil
}

// SetMovie of the movieWriter to the related item.
// Sets o.R.Movie to related.
// Adds o to related.R.MovieWriters.
func (o *MovieWriter) SetMovie(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Movie) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"movie_writer\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"movie_uuid"}),
		strmangle.WhereClause("\"", "\"", 0, movieWriterPrimaryKeyColumns),
	)
	values := []interface{}{related.UUID, o.UUID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.MovieUUID, related.UUID)
	if o.R == nil {
		o.R = &movieWriterR{
			Movie: related,
		}
	} else {
		o.R.Movie = related
	}

	if related.R == nil {
		related.R = &movieR{
			MovieWriters: MovieWriterSlice{o},
		}
	} else {
		related.R.MovieWriters = append(related.R.MovieWriters, o)
	}

	return nil
}

// RemoveMovie relationship.
// Sets o.R.Movie to nil.
// Removes o from all passed in related items' relationships struct.
func (o *MovieWriter) RemoveMovie(ctx context.Context, exec boil.ContextExecutor, related *Movie) error {
	var err error

	queries.SetScanner(&o.MovieUUID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("movie_uuid")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Movie = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.MovieWriters {
		if queries.Equal(o.MovieUUID, ri.MovieUUID) {
			continue
		}

		ln := len(related.R.MovieWriters)
		if ln > 1 && i < ln-1 {
			related.R.MovieWriters[i] = related.R.MovieWriters[ln-1]
		}
		related.R.MovieWriters = related.R.MovieWriters[:ln-1]
		break
	}
	return nil
}

// MovieWriters retrieves all the records using an executor.
func MovieWriters(mods ...qm.QueryMod) movieWriterQuery {
	mods = append(mods, qm.From("\"movie_writer\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"movie_writer\".*"})
	}

	return movieWriterQuery{q}
}

// FindMovieWriter retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindMovieWriter(ctx context.Context, exec boil.ContextExecutor, uUID null.String, selectCols ...string) (*MovieWriter, error) {
	movieWriterObj := &MovieWriter{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"movie_writer\" where \"uuid\"=?", sel,
	)

	q := queries.Raw(query, uUID)

	err := q.Bind(ctx, exec, movieWriterObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from movie_writer")
	}

	return movieWriterObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *MovieWriter) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no movie_writer provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(movieWriterColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	movieWriterInsertCacheMut.RLock()
	cache, cached := movieWriterInsertCache[key]
	movieWriterInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			movieWriterAllColumns,
			movieWriterColumnsWithDefault,
			movieWriterColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(movieWriterType, movieWriterMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(movieWriterType, movieWriterMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"movie_writer\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"movie_writer\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into movie_writer")
	}

	if !cached {
		movieWriterInsertCacheMut.Lock()
		movieWriterInsertCache[key] = cache
		movieWriterInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the MovieWriter.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *MovieWriter) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	movieWriterUpdateCacheMut.RLock()
	cache, cached := movieWriterUpdateCache[key]
	movieWriterUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			movieWriterAllColumns,
			movieWriterPrimaryKeyColumns,
		)
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update movie_writer, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"movie_writer\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, movieWriterPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(movieWriterType, movieWriterMapping, append(wl, movieWriterPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update movie_writer row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for movie_writer")
	}

	if !cached {
		movieWriterUpdateCacheMut.Lock()
		movieWriterUpdateCache[key] = cache
		movieWriterUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q movieWriterQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for movie_writer")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for movie_writer")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o MovieWriterSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), movieWriterPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"movie_writer\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, movieWriterPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in movieWriter slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all movieWriter")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *MovieWriter) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no movie_writer provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(movieWriterColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	movieWriterUpsertCacheMut.RLock()
	cache, cached := movieWriterUpsertCache[key]
	movieWriterUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			movieWriterAllColumns,
			movieWriterColumnsWithDefault,
			movieWriterColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			movieWriterAllColumns,
			movieWriterPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert movie_writer, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(movieWriterPrimaryKeyColumns))
			copy(conflict, movieWriterPrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"movie_writer\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(movieWriterType, movieWriterMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(movieWriterType, movieWriterMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert movie_writer")
	}

	if !cached {
		movieWriterUpsertCacheMut.Lock()
		movieWriterUpsertCache[key] = cache
		movieWriterUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single MovieWriter record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *MovieWriter) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no MovieWriter provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), movieWriterPrimaryKeyMapping)
	sql := "DELETE FROM \"movie_writer\" WHERE \"uuid\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from movie_writer")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for movie_writer")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q movieWriterQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no movieWriterQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from movie_writer")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for movie_writer")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o MovieWriterSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), movieWriterPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"movie_writer\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, movieWriterPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from movieWriter slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for movie_writer")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *MovieWriter) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindMovieWriter(ctx, exec, o.UUID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *MovieWriterSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := MovieWriterSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), movieWriterPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"movie_writer\".* FROM \"movie_writer\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, movieWriterPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in MovieWriterSlice")
	}

	*o = slice

	return nil
}

// MovieWriterExists checks if the MovieWriter row exists.
func MovieWriterExists(ctx context.Context, exec boil.ContextExecutor, uUID null.String) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"movie_writer\" where \"uuid\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, uUID)
	}
	row := exec.QueryRowContext(ctx, sql, uUID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if movie_writer exists")
	}

	return exists, nil
}
