// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// MovieActor is an object representing the database table.
type MovieActor struct {
	UUID            null.String `boil:"uuid" json:"uuid,omitempty" toml:"uuid" yaml:"uuid,omitempty"`
	MovieUUID       null.String `boil:"movie_uuid" json:"movie_uuid,omitempty" toml:"movie_uuid" yaml:"movie_uuid,omitempty"`
	Name            string      `boil:"name" json:"name" toml:"name" yaml:"name"`
	CreatedDatetime int64       `boil:"created_datetime" json:"created_datetime" toml:"created_datetime" yaml:"created_datetime"`

	R *movieActorR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L movieActorL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var MovieActorColumns = struct {
	UUID            string
	MovieUUID       string
	Name            string
	CreatedDatetime string
}{
	UUID:            "uuid",
	MovieUUID:       "movie_uuid",
	Name:            "name",
	CreatedDatetime: "created_datetime",
}

var MovieActorTableColumns = struct {
	UUID            string
	MovieUUID       string
	Name            string
	CreatedDatetime string
}{
	UUID:            "movie_actor.uuid",
	MovieUUID:       "movie_actor.movie_uuid",
	Name:            "movie_actor.name",
	CreatedDatetime: "movie_actor.created_datetime",
}

// Generated where

var MovieActorWhere = struct {
	UUID            whereHelpernull_String
	MovieUUID       whereHelpernull_String
	Name            whereHelperstring
	CreatedDatetime whereHelperint64
}{
	UUID:            whereHelpernull_String{field: "\"movie_actor\".\"uuid\""},
	MovieUUID:       whereHelpernull_String{field: "\"movie_actor\".\"movie_uuid\""},
	Name:            whereHelperstring{field: "\"movie_actor\".\"name\""},
	CreatedDatetime: whereHelperint64{field: "\"movie_actor\".\"created_datetime\""},
}

// MovieActorRels is where relationship names are stored.
var MovieActorRels = struct {
	Movie string
}{
	Movie: "Movie",
}

// movieActorR is where relationships are stored.
type movieActorR struct {
	Movie *Movie `boil:"Movie" json:"Movie" toml:"Movie" yaml:"Movie"`
}

// NewStruct creates a new relationship struct
func (*movieActorR) NewStruct() *movieActorR {
	return &movieActorR{}
}

func (r *movieActorR) GetMovie() *Movie {
	if r == nil {
		return nil
	}
	return r.Movie
}

// movieActorL is where Load methods for each relationship are stored.
type movieActorL struct{}

var (
	movieActorAllColumns            = []string{"uuid", "movie_uuid", "name", "created_datetime"}
	movieActorColumnsWithoutDefault = []string{"name"}
	movieActorColumnsWithDefault    = []string{"uuid", "movie_uuid", "created_datetime"}
	movieActorPrimaryKeyColumns     = []string{"uuid"}
	movieActorGeneratedColumns      = []string{}
)

type (
	// MovieActorSlice is an alias for a slice of pointers to MovieActor.
	// This should almost always be used instead of []MovieActor.
	MovieActorSlice []*MovieActor

	movieActorQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	movieActorType                 = reflect.TypeOf(&MovieActor{})
	movieActorMapping              = queries.MakeStructMapping(movieActorType)
	movieActorPrimaryKeyMapping, _ = queries.BindMapping(movieActorType, movieActorMapping, movieActorPrimaryKeyColumns)
	movieActorInsertCacheMut       sync.RWMutex
	movieActorInsertCache          = make(map[string]insertCache)
	movieActorUpdateCacheMut       sync.RWMutex
	movieActorUpdateCache          = make(map[string]updateCache)
	movieActorUpsertCacheMut       sync.RWMutex
	movieActorUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single movieActor record from the query.
func (q movieActorQuery) One(ctx context.Context, exec boil.ContextExecutor) (*MovieActor, error) {
	o := &MovieActor{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for movie_actor")
	}

	return o, nil
}

// All returns all MovieActor records from the query.
func (q movieActorQuery) All(ctx context.Context, exec boil.ContextExecutor) (MovieActorSlice, error) {
	var o []*MovieActor

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to MovieActor slice")
	}

	return o, nil
}

// Count returns the count of all MovieActor records in the query.
func (q movieActorQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count movie_actor rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q movieActorQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if movie_actor exists")
	}

	return count > 0, nil
}

// Movie pointed to by the foreign key.
func (o *MovieActor) Movie(mods ...qm.QueryMod) movieQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"uuid\" = ?", o.MovieUUID),
	}

	queryMods = append(queryMods, mods...)

	return Movies(queryMods...)
}

// LoadMovie allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (movieActorL) LoadMovie(ctx context.Context, e boil.ContextExecutor, singular bool, maybeMovieActor interface{}, mods queries.Applicator) error {
	var slice []*MovieActor
	var object *MovieActor

	if singular {
		var ok bool
		object, ok = maybeMovieActor.(*MovieActor)
		if !ok {
			object = new(MovieActor)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeMovieActor)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeMovieActor))
			}
		}
	} else {
		s, ok := maybeMovieActor.(*[]*MovieActor)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeMovieActor)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeMovieActor))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &movieActorR{}
		}
		if !queries.IsNil(object.MovieUUID) {
			args = append(args, object.MovieUUID)
		}

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &movieActorR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.MovieUUID) {
					continue Outer
				}
			}

			if !queries.IsNil(obj.MovieUUID) {
				args = append(args, obj.MovieUUID)
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`movie`),
		qm.WhereIn(`movie.uuid in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Movie")
	}

	var resultSlice []*Movie
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Movie")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for movie")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for movie")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Movie = foreign
		if foreign.R == nil {
			foreign.R = &movieR{}
		}
		foreign.R.MovieActors = append(foreign.R.MovieActors, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.MovieUUID, foreign.UUID) {
				local.R.Movie = foreign
				if foreign.R == nil {
					foreign.R = &movieR{}
				}
				foreign.R.MovieActors = append(foreign.R.MovieActors, local)
				break
			}
		}
	}

	return nil
}

// SetMovie of the movieActor to the related item.
// Sets o.R.Movie to related.
// Adds o to related.R.MovieActors.
func (o *MovieActor) SetMovie(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Movie) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"movie_actor\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"movie_uuid"}),
		strmangle.WhereClause("\"", "\"", 0, movieActorPrimaryKeyColumns),
	)
	values := []interface{}{related.UUID, o.UUID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.MovieUUID, related.UUID)
	if o.R == nil {
		o.R = &movieActorR{
			Movie: related,
		}
	} else {
		o.R.Movie = related
	}

	if related.R == nil {
		related.R = &movieR{
			MovieActors: MovieActorSlice{o},
		}
	} else {
		related.R.MovieActors = append(related.R.MovieActors, o)
	}

	return nil
}

// RemoveMovie relationship.
// Sets o.R.Movie to nil.
// Removes o from all passed in related items' relationships struct.
func (o *MovieActor) RemoveMovie(ctx context.Context, exec boil.ContextExecutor, related *Movie) error {
	var err error

	queries.SetScanner(&o.MovieUUID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("movie_uuid")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Movie = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.MovieActors {
		if queries.Equal(o.MovieUUID, ri.MovieUUID) {
			continue
		}

		ln := len(related.R.MovieActors)
		if ln > 1 && i < ln-1 {
			related.R.MovieActors[i] = related.R.MovieActors[ln-1]
		}
		related.R.MovieActors = related.R.MovieActors[:ln-1]
		break
	}
	return nil
}

// MovieActors retrieves all the records using an executor.
func MovieActors(mods ...qm.QueryMod) movieActorQuery {
	mods = append(mods, qm.From("\"movie_actor\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"movie_actor\".*"})
	}

	return movieActorQuery{q}
}

// FindMovieActor retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindMovieActor(ctx context.Context, exec boil.ContextExecutor, uUID null.String, selectCols ...string) (*MovieActor, error) {
	movieActorObj := &MovieActor{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"movie_actor\" where \"uuid\"=?", sel,
	)

	q := queries.Raw(query, uUID)

	err := q.Bind(ctx, exec, movieActorObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from movie_actor")
	}

	return movieActorObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *MovieActor) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no movie_actor provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(movieActorColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	movieActorInsertCacheMut.RLock()
	cache, cached := movieActorInsertCache[key]
	movieActorInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			movieActorAllColumns,
			movieActorColumnsWithDefault,
			movieActorColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(movieActorType, movieActorMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(movieActorType, movieActorMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"movie_actor\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"movie_actor\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into movie_actor")
	}

	if !cached {
		movieActorInsertCacheMut.Lock()
		movieActorInsertCache[key] = cache
		movieActorInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the MovieActor.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *MovieActor) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	movieActorUpdateCacheMut.RLock()
	cache, cached := movieActorUpdateCache[key]
	movieActorUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			movieActorAllColumns,
			movieActorPrimaryKeyColumns,
		)
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update movie_actor, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"movie_actor\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, movieActorPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(movieActorType, movieActorMapping, append(wl, movieActorPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update movie_actor row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for movie_actor")
	}

	if !cached {
		movieActorUpdateCacheMut.Lock()
		movieActorUpdateCache[key] = cache
		movieActorUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q movieActorQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for movie_actor")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for movie_actor")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o MovieActorSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), movieActorPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"movie_actor\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, movieActorPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in movieActor slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all movieActor")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *MovieActor) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no movie_actor provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(movieActorColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	movieActorUpsertCacheMut.RLock()
	cache, cached := movieActorUpsertCache[key]
	movieActorUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			movieActorAllColumns,
			movieActorColumnsWithDefault,
			movieActorColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			movieActorAllColumns,
			movieActorPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert movie_actor, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(movieActorPrimaryKeyColumns))
			copy(conflict, movieActorPrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"movie_actor\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(movieActorType, movieActorMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(movieActorType, movieActorMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert movie_actor")
	}

	if !cached {
		movieActorUpsertCacheMut.Lock()
		movieActorUpsertCache[key] = cache
		movieActorUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single MovieActor record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *MovieActor) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no MovieActor provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), movieActorPrimaryKeyMapping)
	sql := "DELETE FROM \"movie_actor\" WHERE \"uuid\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from movie_actor")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for movie_actor")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q movieActorQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no movieActorQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from movie_actor")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for movie_actor")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o MovieActorSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), movieActorPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"movie_actor\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, movieActorPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from movieActor slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for movie_actor")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *MovieActor) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindMovieActor(ctx, exec, o.UUID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *MovieActorSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := MovieActorSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), movieActorPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"movie_actor\".* FROM \"movie_actor\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, movieActorPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in MovieActorSlice")
	}

	*o = slice

	return nil
}

// MovieActorExists checks if the MovieActor row exists.
func MovieActorExists(ctx context.Context, exec boil.ContextExecutor, uUID null.String) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"movie_actor\" where \"uuid\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, uUID)
	}
	row := exec.QueryRowContext(ctx, sql, uUID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if movie_actor exists")
	}

	return exists, nil
}
