// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// MovieRating is an object representing the database table.
type MovieRating struct {
	UUID            null.String `boil:"uuid" json:"uuid,omitempty" toml:"uuid" yaml:"uuid,omitempty"`
	MovieUUID       null.String `boil:"movie_uuid" json:"movie_uuid,omitempty" toml:"movie_uuid" yaml:"movie_uuid,omitempty"`
	Source          string      `boil:"source" json:"source" toml:"source" yaml:"source"`
	Value           string      `boil:"value" json:"value" toml:"value" yaml:"value"`
	CreatedDatetime int64       `boil:"created_datetime" json:"created_datetime" toml:"created_datetime" yaml:"created_datetime"`

	R *movieRatingR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L movieRatingL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var MovieRatingColumns = struct {
	UUID            string
	MovieUUID       string
	Source          string
	Value           string
	CreatedDatetime string
}{
	UUID:            "uuid",
	MovieUUID:       "movie_uuid",
	Source:          "source",
	Value:           "value",
	CreatedDatetime: "created_datetime",
}

var MovieRatingTableColumns = struct {
	UUID            string
	MovieUUID       string
	Source          string
	Value           string
	CreatedDatetime string
}{
	UUID:            "movie_rating.uuid",
	MovieUUID:       "movie_rating.movie_uuid",
	Source:          "movie_rating.source",
	Value:           "movie_rating.value",
	CreatedDatetime: "movie_rating.created_datetime",
}

// Generated where

var MovieRatingWhere = struct {
	UUID            whereHelpernull_String
	MovieUUID       whereHelpernull_String
	Source          whereHelperstring
	Value           whereHelperstring
	CreatedDatetime whereHelperint64
}{
	UUID:            whereHelpernull_String{field: "\"movie_rating\".\"uuid\""},
	MovieUUID:       whereHelpernull_String{field: "\"movie_rating\".\"movie_uuid\""},
	Source:          whereHelperstring{field: "\"movie_rating\".\"source\""},
	Value:           whereHelperstring{field: "\"movie_rating\".\"value\""},
	CreatedDatetime: whereHelperint64{field: "\"movie_rating\".\"created_datetime\""},
}

// MovieRatingRels is where relationship names are stored.
var MovieRatingRels = struct {
	Movie string
}{
	Movie: "Movie",
}

// movieRatingR is where relationships are stored.
type movieRatingR struct {
	Movie *Movie `boil:"Movie" json:"Movie" toml:"Movie" yaml:"Movie"`
}

// NewStruct creates a new relationship struct
func (*movieRatingR) NewStruct() *movieRatingR {
	return &movieRatingR{}
}

func (r *movieRatingR) GetMovie() *Movie {
	if r == nil {
		return nil
	}
	return r.Movie
}

// movieRatingL is where Load methods for each relationship are stored.
type movieRatingL struct{}

var (
	movieRatingAllColumns            = []string{"uuid", "movie_uuid", "source", "value", "created_datetime"}
	movieRatingColumnsWithoutDefault = []string{"source", "value"}
	movieRatingColumnsWithDefault    = []string{"uuid", "movie_uuid", "created_datetime"}
	movieRatingPrimaryKeyColumns     = []string{"uuid"}
	movieRatingGeneratedColumns      = []string{}
)

type (
	// MovieRatingSlice is an alias for a slice of pointers to MovieRating.
	// This should almost always be used instead of []MovieRating.
	MovieRatingSlice []*MovieRating

	movieRatingQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	movieRatingType                 = reflect.TypeOf(&MovieRating{})
	movieRatingMapping              = queries.MakeStructMapping(movieRatingType)
	movieRatingPrimaryKeyMapping, _ = queries.BindMapping(movieRatingType, movieRatingMapping, movieRatingPrimaryKeyColumns)
	movieRatingInsertCacheMut       sync.RWMutex
	movieRatingInsertCache          = make(map[string]insertCache)
	movieRatingUpdateCacheMut       sync.RWMutex
	movieRatingUpdateCache          = make(map[string]updateCache)
	movieRatingUpsertCacheMut       sync.RWMutex
	movieRatingUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single movieRating record from the query.
func (q movieRatingQuery) One(ctx context.Context, exec boil.ContextExecutor) (*MovieRating, error) {
	o := &MovieRating{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for movie_rating")
	}

	return o, nil
}

// All returns all MovieRating records from the query.
func (q movieRatingQuery) All(ctx context.Context, exec boil.ContextExecutor) (MovieRatingSlice, error) {
	var o []*MovieRating

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to MovieRating slice")
	}

	return o, nil
}

// Count returns the count of all MovieRating records in the query.
func (q movieRatingQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count movie_rating rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q movieRatingQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if movie_rating exists")
	}

	return count > 0, nil
}

// Movie pointed to by the foreign key.
func (o *MovieRating) Movie(mods ...qm.QueryMod) movieQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"uuid\" = ?", o.MovieUUID),
	}

	queryMods = append(queryMods, mods...)

	return Movies(queryMods...)
}

// LoadMovie allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (movieRatingL) LoadMovie(ctx context.Context, e boil.ContextExecutor, singular bool, maybeMovieRating interface{}, mods queries.Applicator) error {
	var slice []*MovieRating
	var object *MovieRating

	if singular {
		var ok bool
		object, ok = maybeMovieRating.(*MovieRating)
		if !ok {
			object = new(MovieRating)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeMovieRating)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeMovieRating))
			}
		}
	} else {
		s, ok := maybeMovieRating.(*[]*MovieRating)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeMovieRating)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeMovieRating))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &movieRatingR{}
		}
		if !queries.IsNil(object.MovieUUID) {
			args = append(args, object.MovieUUID)
		}

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &movieRatingR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.MovieUUID) {
					continue Outer
				}
			}

			if !queries.IsNil(obj.MovieUUID) {
				args = append(args, obj.MovieUUID)
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`movie`),
		qm.WhereIn(`movie.uuid in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Movie")
	}

	var resultSlice []*Movie
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Movie")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for movie")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for movie")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Movie = foreign
		if foreign.R == nil {
			foreign.R = &movieR{}
		}
		foreign.R.MovieRatings = append(foreign.R.MovieRatings, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.MovieUUID, foreign.UUID) {
				local.R.Movie = foreign
				if foreign.R == nil {
					foreign.R = &movieR{}
				}
				foreign.R.MovieRatings = append(foreign.R.MovieRatings, local)
				break
			}
		}
	}

	return nil
}

// SetMovie of the movieRating to the related item.
// Sets o.R.Movie to related.
// Adds o to related.R.MovieRatings.
func (o *MovieRating) SetMovie(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Movie) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"movie_rating\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"movie_uuid"}),
		strmangle.WhereClause("\"", "\"", 0, movieRatingPrimaryKeyColumns),
	)
	values := []interface{}{related.UUID, o.UUID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.MovieUUID, related.UUID)
	if o.R == nil {
		o.R = &movieRatingR{
			Movie: related,
		}
	} else {
		o.R.Movie = related
	}

	if related.R == nil {
		related.R = &movieR{
			MovieRatings: MovieRatingSlice{o},
		}
	} else {
		related.R.MovieRatings = append(related.R.MovieRatings, o)
	}

	return nil
}

// RemoveMovie relationship.
// Sets o.R.Movie to nil.
// Removes o from all passed in related items' relationships struct.
func (o *MovieRating) RemoveMovie(ctx context.Context, exec boil.ContextExecutor, related *Movie) error {
	var err error

	queries.SetScanner(&o.MovieUUID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("movie_uuid")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Movie = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.MovieRatings {
		if queries.Equal(o.MovieUUID, ri.MovieUUID) {
			continue
		}

		ln := len(related.R.MovieRatings)
		if ln > 1 && i < ln-1 {
			related.R.MovieRatings[i] = related.R.MovieRatings[ln-1]
		}
		related.R.MovieRatings = related.R.MovieRatings[:ln-1]
		break
	}
	return nil
}

// MovieRatings retrieves all the records using an executor.
func MovieRatings(mods ...qm.QueryMod) movieRatingQuery {
	mods = append(mods, qm.From("\"movie_rating\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"movie_rating\".*"})
	}

	return movieRatingQuery{q}
}

// FindMovieRating retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindMovieRating(ctx context.Context, exec boil.ContextExecutor, uUID null.String, selectCols ...string) (*MovieRating, error) {
	movieRatingObj := &MovieRating{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"movie_rating\" where \"uuid\"=?", sel,
	)

	q := queries.Raw(query, uUID)

	err := q.Bind(ctx, exec, movieRatingObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from movie_rating")
	}

	return movieRatingObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *MovieRating) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no movie_rating provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(movieRatingColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	movieRatingInsertCacheMut.RLock()
	cache, cached := movieRatingInsertCache[key]
	movieRatingInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			movieRatingAllColumns,
			movieRatingColumnsWithDefault,
			movieRatingColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(movieRatingType, movieRatingMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(movieRatingType, movieRatingMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"movie_rating\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"movie_rating\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into movie_rating")
	}

	if !cached {
		movieRatingInsertCacheMut.Lock()
		movieRatingInsertCache[key] = cache
		movieRatingInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the MovieRating.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *MovieRating) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	movieRatingUpdateCacheMut.RLock()
	cache, cached := movieRatingUpdateCache[key]
	movieRatingUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			movieRatingAllColumns,
			movieRatingPrimaryKeyColumns,
		)
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update movie_rating, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"movie_rating\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, movieRatingPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(movieRatingType, movieRatingMapping, append(wl, movieRatingPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update movie_rating row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for movie_rating")
	}

	if !cached {
		movieRatingUpdateCacheMut.Lock()
		movieRatingUpdateCache[key] = cache
		movieRatingUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q movieRatingQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for movie_rating")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for movie_rating")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o MovieRatingSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), movieRatingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"movie_rating\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, movieRatingPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in movieRating slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all movieRating")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *MovieRating) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no movie_rating provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(movieRatingColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	movieRatingUpsertCacheMut.RLock()
	cache, cached := movieRatingUpsertCache[key]
	movieRatingUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			movieRatingAllColumns,
			movieRatingColumnsWithDefault,
			movieRatingColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			movieRatingAllColumns,
			movieRatingPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert movie_rating, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(movieRatingPrimaryKeyColumns))
			copy(conflict, movieRatingPrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"movie_rating\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(movieRatingType, movieRatingMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(movieRatingType, movieRatingMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert movie_rating")
	}

	if !cached {
		movieRatingUpsertCacheMut.Lock()
		movieRatingUpsertCache[key] = cache
		movieRatingUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single MovieRating record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *MovieRating) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no MovieRating provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), movieRatingPrimaryKeyMapping)
	sql := "DELETE FROM \"movie_rating\" WHERE \"uuid\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from movie_rating")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for movie_rating")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q movieRatingQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no movieRatingQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from movie_rating")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for movie_rating")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o MovieRatingSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), movieRatingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"movie_rating\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, movieRatingPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from movieRating slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for movie_rating")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *MovieRating) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindMovieRating(ctx, exec, o.UUID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *MovieRatingSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := MovieRatingSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), movieRatingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"movie_rating\".* FROM \"movie_rating\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, movieRatingPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in MovieRatingSlice")
	}

	*o = slice

	return nil
}

// MovieRatingExists checks if the MovieRating row exists.
func MovieRatingExists(ctx context.Context, exec boil.ContextExecutor, uUID null.String) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"movie_rating\" where \"uuid\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, uUID)
	}
	row := exec.QueryRowContext(ctx, sql, uUID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if movie_rating exists")
	}

	return exists, nil
}
