// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Movies", testMoviesUpsert)

	t.Run("MovieActors", testMovieActorsUpsert)

	t.Run("MovieDirectors", testMovieDirectorsUpsert)

	t.Run("MovieGenres", testMovieGenresUpsert)

	t.Run("MovieRatings", testMovieRatingsUpsert)

	t.Run("MovieWatches", testMovieWatchesUpsert)

	t.Run("MovieWriters", testMovieWritersUpsert)
}
